### ISSUE TITLE
Missing Implementation

### ISSUE THREAD

**Issue by benedekrozemberczki** [sarpaykent/GBPNet#1]
This paper appears in the KDD 2022 proceedings. In the published paper you claim that the code is available here. It is not. Do you plan to release the code?

**Comment by amorehead** [comment]
I second this. I would be curious to see the source code.

**Comment by sarpaykent** [comment]
Hi @benedekrozemberczki, thank you for your interest, and apologies for the delay. Due to traveling reasons, I didn't have a chance to check the code for the publication. There are some version issues with the dependencies, I'm updating the dependencies and modifying the deprecated parts. I'll be reproducing the results with the modifications and will be pushing the code tomorrow latest.
